---

- name: Install apt-transport-https to support https APT downloads
  apt: name=apt-transport-https state=present

- name: Add Elasticsearch repository key
  apt_key: url="{{ es_apt_key }}" state=present

- name: Add elasticsearch repository
  apt_repository: repo={{ es_apt_url }} state=present

- name: Install logstash
  apt: name=logstash state=present

- name: Copy logstash configuration files
  copy:
    src: "{{ item }}"
    dest: /etc/logstash/conf.d/
    owner: root
    group: root
    mode: 0644
  with_items:
    - 01-suricata.conf

- name: Create template directory
  file:
    path: /etc/logstash/templates
    state: directory
    mode: '0744'

- name: Copy template file
  copy:
    src: ../files/templates/suricata.json
    dest: /etc/logstash/templates/suricata.json
    owner: root
    group: root
    mode: '0644'

- name: Start logstash
  systemd:
    name: logstash
    daemon_reload: yes
    state: started
    enabled: yes
